---
  - name: Update APT package cache
    apt: update_cache=yes cache_valid_time=600
    tags: apt

  - name: Upgrade APT to the latest packages
    apt: upgrade=dist
    register: apt_result
    tags: apt

  - name: Autoremove unused packages
    command: apt -y autoremove
    register: apt_result
    changed_when: "'packages will be REMOVED' in apt_result.stdout"
    tags: apt

  - name: Purge residual kernel packages
    shell: apt-get remove -y --purge $(dpkg -l | grep "^rc\s*linux-image-" | awk '{print $2}' | tr '\n' ' ')
    register: apt_result
    changed_when: "'packages will be REMOVED' in apt_result.stdout"
    tags: apt

  - name: Install base packages
    apt: 
     pkg:
     - vim
     - telnet
     - nmap
     - sysstat
    tags: apt
